### ISSUE TITLE
Yosemite update broke this?

### ISSUE THREAD

**Issue by vanrijn** [bjornhusberg/wallpaper#1]
Hey bro. I have been using your script for a while, but it looks like it doesn't work with Yosemite anymore?

**Comment by bjornhusberg** [comment]
Works on my Yosemite machine. What problems are you experiencing?

**Comment by vanrijn** [comment]
And of course, now it works. >_< I think the problem was that until you change your wallpaper at least once through System Preferences, this doesn't work. Anyway, it seems to be working fine now. Sorry for the confusion. =:)

**Comment by bjornhusberg** [comment]
Oh, yep. That's a known (but undocumented) bug.
